In [1]:
# Import Required Libraries
#import pandas as pd
import numpy as np


In [16]:
#1 Load dataset
#Dataset is on my public github repository, 
#don't need to download it, just use the link to access it

url = "https://raw.githubusercontent.com/AUunkle/ML_in_data/main/hw2/iris.data"
df = np.genfromtxt(url, delimiter=",",dtype=float, usecols=[0, 1, 2, 3])


In [17]:
#2 Check the shape of the dataset
if df.ndim != 2:
    df = df.reshape(-1, 4)
  

In [18]:
 #3 Calculate mean, median, standard deviation for the 1-st column of the dataset
meanVal = np.mean(df[:, 0])
medianVal = np.median(df[:, 0])
stdVal = np.std(df[:, 0])

print(meanVal)
print(medianVal)
print(stdVal)

5.843333333333334
5.8
0.8253012917851409


In [19]:
#4 change to NaN  20 random elements by unique index
nanInd = np.random.choice(df.size, 20, replace=False)

df[np.unravel_index(nanInd, df.shape)] = np.nan
print(df)

[[5.1 3.5 nan 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [nan 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [nan 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [nan 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 nan 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 nan 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [nan 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 nan]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [nan 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [20]:
#5 define pos's  of nan in 1-st column

nanInd_1_clmn = np.where(np.isnan(df[:, 0]))
print(nanInd_1_clmn)

(array([  9,  13,  18,  38,  48,  95, 100, 118]),)


In [21]:
#6 filtered array by statement: value > 1.5  in the 3-rd clmn, value  < 5.0 in the 1-st clmn (зберегти у іншу змінну)

flt_df = df[(df[:, 2] > 1.5 ) & (df[:, 0] < 5.0)]

print( flt_df)

[[4.8 3.4 1.6 0.2]
 [4.8 nan 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [22]:
#7 change nan to 0.0
df = np.nan_to_num(df, nan=0.0)
print (df)


[[5.1 3.5 0.  0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [0.  3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [0.  3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [0.  3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 0.  1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 0.  0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0. ]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [0.  3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [25]:
#8 count all unique values
uniqueVal, counts = np.unique(df, return_counts=True)
dictUniqVal = dict(zip(uniqueVal, counts))
np.set_printoptions(legacy="1.25")
print(dictUniqVal)



{0.0: 20, 0.1: 6, 0.2: 28, 0.3: 6, 0.4: 7, 0.5: 1, 0.6: 1, 1.0: 8, 1.1: 4, 1.2: 7, 1.3: 19, 1.4: 19, 1.5: 25, 1.6: 10, 1.7: 6, 1.8: 12, 1.9: 7, 2.0: 7, 2.1: 6, 2.2: 6, 2.3: 12, 2.4: 5, 2.5: 11, 2.6: 5, 2.7: 8, 2.8: 14, 2.9: 10, 3.0: 27, 3.1: 11, 3.2: 13, 3.3: 8, 3.4: 10, 3.5: 8, 3.6: 4, 3.7: 4, 3.8: 7, 3.9: 5, 4.0: 5, 4.1: 4, 4.2: 5, 4.3: 2, 4.4: 7, 4.5: 8, 4.6: 7, 4.7: 7, 4.8: 9, 4.9: 10, 5.0: 14, 5.1: 17, 5.2: 6, 5.3: 2, 5.4: 8, 5.5: 10, 5.6: 12, 5.7: 9, 5.8: 10, 5.9: 5, 6.0: 8, 6.1: 9, 6.2: 4, 6.3: 9, 6.4: 8, 6.5: 5, 6.6: 3, 6.7: 10, 6.8: 3, 6.9: 5, 7.0: 1, 7.1: 1, 7.2: 3, 7.3: 1, 7.4: 1, 7.6: 1, 7.7: 3, 7.9: 1}


In [26]:
#9 split the dataset into 2 equal parts by rows
df1, df2 = np.array_split(df, 2, axis=0)
print(df1)
print("-------------------")
print(df2)

[[5.1 3.5 0.  0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [0.  3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [0.  3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [0.  3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 0.  1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 0.  0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [0.  3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0. ]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [0.  3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [27]:
#10 sort by the 1-st column df1 acsending, df2 descending orders
df1 = df1[np.argsort(df1[:, 0])]
df2 = df2[np.argsort(df2[:, 0])[::-1]]
print(df1)
print("-------------------")
print(df2)

[[0.  3.  1.1 0.1]
 [0.  3.1 1.5 0.1]
 [0.  3.8 1.7 0.3]
 [0.  3.  1.3 0.2]
 [0.  3.7 1.5 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0. ]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 0.  1.9 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.6 0.4]
 [5.  3.  1.6 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.6 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.1 3.5 0.  0.2]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.4 1.5 0.4]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.6 3.  4.

In [28]:
#11 concatenate df1 and df2
dfCnct = np.concatenate((df1, df2))
print(dfCnct)

[[0.  3.  1.1 0.1]
 [0.  3.1 1.5 0.1]
 [0.  3.8 1.7 0.3]
 [0.  3.  1.3 0.2]
 [0.  3.7 1.5 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0. ]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 0.  1.9 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.6 0.4]
 [5.  3.  1.6 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.6 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.1 3.5 0.  0.2]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.4 1.5 0.4]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.6 3.  4.

In [29]:
#12 find the most repetable element df_concatenated
uniqueVal, counts = np.unique(dfCnct, return_counts=True)
max_count = np.max(counts)
mostRpt = uniqueVal[counts == max_count]

print(mostRpt)


[0.2]


In [30]:
#13 function that multiply by 2 all el less then mean and divide by 4 above the mean separatly for each column
def change2by4Rule(_df, _clmn=-1):
    means = np.mean(_df, axis=0)

    if _clmn == -1:
        for i in range(_df.shape[1]):
            _df[:,i] = np.where(_df[:,i] < means[i], _df[:,i] * 2, _df[:,i] / 4)
    else :
        _df[:, _clmn] = np.where(_df[:, _clmn] < means[_clmn], _df[:, _clmn] * 2, _df[:, _clmn] / 4)
        
    return _df


In [31]:
#14 apply function for the 3-rd column of the dataset
print(dfCnct)
change2by4Rule(dfCnct,2)
print("-------------------")
print(dfCnct)

[[0.  3.  1.1 0.1]
 [0.  3.1 1.5 0.1]
 [0.  3.8 1.7 0.3]
 [0.  3.  1.3 0.2]
 [0.  3.7 1.5 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0. ]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 0.  1.9 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.6 0.4]
 [5.  3.  1.6 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.6 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.1 3.5 0.  0.2]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.4 1.5 0.4]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.6 3.  4.